#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOCKER_DIR="$SCRIPT_DIR/../docker"
AGENTIR_DIR="$HOME/.agentir"
CONFIG_FILE="$AGENTIR_DIR/opensearch.yaml"
OS_URL="https://localhost:9200"

# --- 1. Check Docker ---
if ! command -v docker &>/dev/null; then
    echo "Error: Docker is not installed."
    echo "Install Docker: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo "Error: Docker Compose (v2) is not available."
    exit 1
fi

if ! docker ps &>/dev/null; then
    if ! groups | grep -qw docker; then
        echo "Adding $USER to docker group (requires sudo)..."
        if sudo usermod -aG docker "$USER"; then
            echo "Re-running with docker group access..."
            exec sg docker -c 'bash "'"$0"'"'
        else
            echo "Error: Could not add $USER to docker group."
            echo "  Run manually: sudo usermod -aG docker $USER && newgrp docker"
            exit 1
        fi
    else
        echo "Docker daemon not running. Starting..."
        sudo systemctl start docker
        if ! docker ps &>/dev/null; then
            echo "Error: Could not start Docker daemon."
            exit 1
        fi
    fi
fi

echo "Docker $(docker --version | grep -oP '\d+\.\d+\.\d+')"

# --- 2. Generate password ---
mkdir -p "$AGENTIR_DIR"
if [ -f "$CONFIG_FILE" ]; then
    echo "OpenSearch config exists: $CONFIG_FILE"
    OS_PASSWORD=$(python3 -c "import yaml; print(yaml.safe_load(open('$CONFIG_FILE'))['password'])")
else
    # Generate password that passes zxcvbn score >= 3
    OS_PASSWORD="Vhir_$(openssl rand -hex 12)"
    cat > "$CONFIG_FILE" <<EOF
# Generated by setup-opensearch.sh — do not edit manually
host: https://localhost:9200
user: admin
password: $OS_PASSWORD
verify_certs: false
EOF
    chmod 600 "$CONFIG_FILE"
    echo "Generated OpenSearch config: $CONFIG_FILE"
fi

# --- 2b. Configure snapshot support for backup/restore ---
SNAPSHOTS_DIR="/var/lib/agentir/snapshots"
OVERRIDE_FILE="$DOCKER_DIR/docker-compose.override.yml"

if [ ! -d "$SNAPSHOTS_DIR" ]; then
    echo "Creating snapshot directory ($SNAPSHOTS_DIR)..."
    sudo mkdir -p "$SNAPSHOTS_DIR"
    # UID 1000 = opensearch user inside the Docker container
    sudo chown 1000:1000 "$SNAPSHOTS_DIR"
    echo "  Snapshot directory: OK"
fi

if [ ! -f "$OVERRIDE_FILE" ]; then
    echo "Creating docker-compose.override.yml for snapshot volume..."
    cat > "$OVERRIDE_FILE" <<OVERRIDE
# Snapshot volume mount for agentir backup/restore
# Added by setup-opensearch.sh — do not modify the main docker-compose.yml
services:
  opensearch:
    volumes:
      - /var/lib/agentir/snapshots:/usr/share/opensearch/snapshots
OVERRIDE
    echo "  Override file: OK"
else
    echo "docker-compose.override.yml exists — checking snapshot volume..."
    if grep -q "/var/lib/agentir/snapshots" "$OVERRIDE_FILE"; then
        echo "  Snapshot volume: already configured"
    else
        echo "  WARNING: Override file exists but snapshot volume not configured."
        echo "  Add manually to $OVERRIDE_FILE:"
        echo "    services:"
        echo "      opensearch:"
        echo "        volumes:"
        echo "          - /var/lib/agentir/snapshots:/usr/share/opensearch/snapshots"
    fi
fi

# --- 3. Start OpenSearch ---
export AGENTIR_OS_PASSWORD="$OS_PASSWORD"
echo "Starting OpenSearch..."
docker compose -f "$DOCKER_DIR/docker-compose.yml" up -d

# --- 4. Wait for OpenSearch to be ready ---
echo -n "Waiting for OpenSearch"
STATUS="unknown"
for i in $(seq 1 90); do
    HEALTH=$(curl -sk -u "admin:$OS_PASSWORD" "$OS_URL/_cluster/health" 2>/dev/null || true)
    STATUS=$(echo "$HEALTH" | python3 -c "import sys,json; print(json.load(sys.stdin).get('status','unknown'))" 2>/dev/null || echo "unknown")
    if [ "$STATUS" = "green" ] || [ "$STATUS" = "yellow" ]; then
        echo " ready!"
        break
    fi
    echo -n "."
    sleep 2
done

if [ "$STATUS" != "green" ] && [ "$STATUS" != "yellow" ]; then
    echo ""
    echo "Error: OpenSearch not ready after 180 seconds (status: $STATUS)."
    echo "Check: docker logs agentir-opensearch"
    exit 1
fi
echo "Cluster status: $STATUS"

# --- Configure snapshot repository path ---
echo "Configuring snapshot repository path..."
curl -sk -u "admin:$OS_PASSWORD" -X PUT "$OS_URL/_cluster/settings" \
    -H "Content-Type: application/json" \
    -d '{"persistent":{"path.repo":["/usr/share/opensearch/snapshots"]}}' >/dev/null 2>&1
echo "  path.repo: /usr/share/opensearch/snapshots"

# --- Raise shard limit for multi-case deployments ---
echo "Configuring cluster settings..."
curl -sk -u "admin:$OS_PASSWORD" -X PUT "$OS_URL/_cluster/settings" \
    -H "Content-Type: application/json" \
    -d '{"persistent":{"cluster.max_shards_per_node":3000}}' >/dev/null 2>&1
echo "  max_shards_per_node: 3000"

# --- 5. Index templates ---
#
# Removed 2026-04-22: template + agentir-single-node catch-all installs
# previously done here are now handled by
# src/opensearch_mcp/mappings/__init__.py (ensure_winlog_pipeline +
# install_all_templates) at every MCP startup and ingest pre-flight.
# That makes template edits on disk reach deployed clusters without
# re-running this script. Having both paths install templates was a
# drift trap: a template added to the registry but forgotten here (or
# vice versa) left one installer in the wrong state.
#
# Every case-* template now declares index.number_of_replicas: 0
# explicitly, so the priority-1 agentir-single-node catch-all that used
# to live here is obsolete.
echo "Index templates: installed by opensearch-mcp at MCP startup (see ensure_winlog_pipeline)."

# --- 6. Smoke test ---
echo "Running smoke test..."
# Index a test doc
curl -sk -u "admin:$OS_PASSWORD" \
    -X POST "$OS_URL/case-test-evtx-smoketest/_doc/test-1?refresh=true" \
    -H "Content-Type: application/json" \
    -d '{"event.code":4624,"@timestamp":"2024-01-01T00:00:00Z","host.name":"test"}' \
    >/dev/null 2>&1

# Search for it
FOUND=$(curl -sk -u "admin:$OS_PASSWORD" \
    "$OS_URL/case-test-evtx-smoketest/_search?q=event.code:4624&size=1" 2>/dev/null \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['hits']['total']['value'])" 2>/dev/null || echo "0")

if [ "$FOUND" = "1" ]; then
    echo "  Smoke test: PASS"
else
    echo "  Smoke test: FAIL (expected 1 hit, got $FOUND)"
fi

# Clean up test index
curl -sk -u "admin:$OS_PASSWORD" -X DELETE "$OS_URL/case-test-evtx-smoketest" >/dev/null 2>&1

# --- 7. GeoIP enrichment (Phase 4) ---
echo "Configuring GeoIP enrichment..."

# Create GeoIP data source (requires internet for initial download)
GEO_RESULT=$(curl -sk -u "admin:$OS_PASSWORD" \
    -X PUT "$OS_URL/_plugins/geospatial/ip2geo/datasource/maxmind-city" \
    -H "Content-Type: application/json" \
    -d '{"endpoint":"https://geoip.maps.opensearch.org/v1/geolite2-city/manifest.json","update_interval_in_days":3}' 2>/dev/null || echo '{"error":"failed"}')
if echo "$GEO_RESULT" | python3 -c "import sys,json; r=json.load(sys.stdin); sys.exit(0 if r.get('acknowledged') else 1)" 2>/dev/null; then
    echo "  GeoIP data source: OK"
else
    echo "  GeoIP data source: skipped (requires internet or already exists)"
fi

# Create GeoIP ingest pipeline with on_failure handler
echo "Creating GeoIP ingest pipeline..."
curl -sk -u "admin:$OS_PASSWORD" \
    -X PUT "$OS_URL/_ingest/pipeline/agentir-geoip" \
    -H "Content-Type: application/json" \
    -d '{
  "description": "GeoIP enrichment for source.ip",
  "processors": [{
    "ip2geo": {
      "field": "source.ip",
      "datasource": "maxmind-city",
      "target_field": "source.geo",
      "ignore_missing": true,
      "on_failure": [{
        "set": {
          "field": "source.geo.error",
          "value": "GeoIP lookup failed: {{_ingest.on_failure_message}}"
        }
      }]
    }
  }]
}' | python3 -c "import sys,json; r=json.load(sys.stdin); print('  Pipeline:', 'OK' if r.get('acknowledged') else r)" 2>/dev/null

# Apply GeoIP pipeline to indices with IP fields (decoupled from templates)
for PATTERN in "case-*-evtx-*" "case-*-iis-*" "case-*-httperr-*" "case-*-firewall-*" "case-*-ssh-*" "case-*-accesslog-*"; do
    curl -sk -u "admin:$OS_PASSWORD" \
        -X PUT "$OS_URL/$PATTERN/_settings" \
        -H "Content-Type: application/json" \
        -d '{"index.default_pipeline":"agentir-geoip"}' >/dev/null 2>&1 || true
done
echo "  Applied GeoIP pipeline to IP-bearing indices"

# --- 8. Security Analytics detector (Phase 4) ---
echo "Configuring Security Analytics..."

# Fetch all Windows pre-packaged Sigma rule IDs, create detector
python3 -c "
import json, sys, time, urllib.request, ssl

url = '$OS_URL'
auth = 'admin:$OS_PASSWORD'

import base64
creds = base64.b64encode(auth.encode()).decode()
headers = {
    'Authorization': f'Basic {creds}',
    'Content-Type': 'application/json',
}
ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

def api(method, path, body=None):
    data = json.dumps(body).encode() if body else None
    req = urllib.request.Request(url + path, data=data, headers=headers, method=method)
    with urllib.request.urlopen(req, context=ctx) as resp:
        return json.loads(resp.read())

# Step 1: Wait for pre-packaged rules to load (async after cluster start)
rule_ids = []
for attempt in range(6):
    try:
        resp = api('POST', '/_plugins/_security_analytics/rules/_search?pre_packaged=true', {
            'query': {'match_all': {}},
            'size': 5000,
        })
        hits = resp.get('hits', {}).get('hits', [])
        rule_ids = [{'id': h['_id']} for h in hits if h.get('_source', {}).get('category') == 'windows']
        if rule_ids:
            print(f'  Found {len(rule_ids)} Windows Sigma rules (from {len(hits)} total)')
            break
        if hits:
            print(f'  Found {len(hits)} rules but 0 Windows category')
            break
        if attempt < 5:
            print(f'  Waiting for Sigma rules to load ({attempt + 1}/6)...')
            time.sleep(10)
    except Exception as e:
        if attempt < 5:
            print(f'  Rules API not ready ({e}), retrying...')
            time.sleep(10)
        else:
            print(f'  Warning: Could not fetch Sigma rules after 6 attempts: {e}')
            sys.exit(0)

if not rule_ids:
    print('  No Windows Sigma rules found — skipping detector creation')
    sys.exit(0)

# Step 2: Fetch existing detectors (one API call for all categories)
existing_detectors = set()
try:
    existing = api('POST', '/_plugins/_security_analytics/detectors/_search', {
        'query': {'match_all': {}},
        'size': 100,
    })
    for hit in existing.get('hits', {}).get('hits', []):
        existing_detectors.add(hit.get('_source', {}).get('name', ''))
except Exception:
    pass

# Step 2b: Create seed indices to instantiate aliases from templates.
# Detectors on 3.x require aliases to exist (backed by at least one index).
# Templates auto-attach aliases when matching indices are created.
_SEEDS = {
    'case-seed-evtx-init': 'agentir-sigma-windows',
    'case-seed-ssh-init': 'agentir-sigma-linux',
    'case-seed-accesslog-init': 'agentir-sigma-web',
    'case-seed-json-init': 'agentir-sigma-network',
}
for seed_idx, alias in _SEEDS.items():
    try:
        api('PUT', f'/{seed_idx}', {'settings': {'number_of_replicas': 0}})
    except Exception:
        pass  # Already exists or template not registered yet

# Step 3: Sigma detectors disabled on OpenSearch 3.5
# The Security Analytics percolator has a field alias regression
# (opensearch-project/security-analytics#755) that produces 0 findings.
# Detection is handled by Hayabusa instead (runs during evtx ingest).
from collections import Counter
cat_counts = Counter(h.get('_source', {}).get('category', '') for h in hits)
print(f'  Sigma detectors: disabled (OpenSearch 3.5 field alias regression)')
win_count = cat_counts.get('windows', 0)
print(f'  Available rules: {len(hits)} ({win_count} Windows)')
print(f'  Detection via Hayabusa during evtx ingest (if installed)')

# Delete any existing detectors (produce 0 findings, waste CPU)
for det_name in list(existing_detectors):
    if det_name.startswith('agentir-'):
        try:
            for hit in existing.get('hits', {}).get('hits', []):
                if hit.get('_source', {}).get('name') == det_name:
                    det_id = hit['_id']
                    api('DELETE', f'/_plugins/_security_analytics/detectors/{det_id}')
                    print(f'  Removed non-functional detector: {det_name}')
                    break
        except Exception:
            pass

# Clean up orphaned monitors from pre-3.5 detector attempts (BUG-R4)
try:
    monitors = api('GET', '/_plugins/_alerting/monitors/_search',
                    body=json.dumps({"query": {"match_all": {}}, "size": 50}))
    for hit in monitors.get('hits', {}).get('hits', []):
        name = hit.get('_source', {}).get('name', '')
        if name.startswith('agentir-') or name.startswith('sigma_'):
            mon_id = hit['_id']
            api('DELETE', f'/_plugins/_alerting/monitors/{mon_id}')
            print(f'  Removed orphaned monitor: {name}')
except Exception:
    pass  # Alerting plugin may not be installed

# Add aliases to existing indices (upgrade from pre-alias versions)
_ALIAS_PATTERNS = {
    'agentir-sigma-windows': 'case-*-evtx-*',
    'agentir-sigma-linux': 'case-*-ssh-*',
    'agentir-sigma-web': 'case-*-accesslog-*',
    'agentir-sigma-network': 'case-*-json-*',
}
for alias, pattern in _ALIAS_PATTERNS.items():
    try:
        api('POST', '/_aliases', {
            'actions': [{'add': {'index': pattern, 'alias': alias}}]
        })
    except Exception:
        pass  # No matching indices yet — aliases auto-attach via templates
" || echo "  Security Analytics setup: skipped (may require manual configuration)"

# --- 9. Register opensearch-mcp with gateway ---
GW_CONFIG="$AGENTIR_DIR/gateway.yaml"
if [ -f "$GW_CONFIG" ]; then
    if grep -q "opensearch-mcp" "$GW_CONFIG"; then
        echo "opensearch-mcp already registered in gateway config."
    else
        echo "Registering opensearch-mcp with gateway..."
        # Append opensearch-mcp backend entry
        # Insert under backends: key using Python for safe YAML manipulation
        # Use venv python (matches setup-sift.sh), not system python
        VENV_PYTHON="$AGENTIR_DIR/venv/bin/python"
        if [ ! -f "$VENV_PYTHON" ]; then
            VENV_PYTHON="$(which python3)"
            echo "  Warning: venv not found at $AGENTIR_DIR/venv — using system python3"
        fi
        "$VENV_PYTHON" -c "
import yaml
from pathlib import Path
p = Path('$GW_CONFIG')
config = yaml.safe_load(p.read_text()) or {}
backends = config.setdefault('backends', {})
backends['opensearch-mcp'] = {
    'type': 'stdio',
    'command': '$VENV_PYTHON',
    'args': ['-m', 'opensearch_mcp'],
    'env': {'OPENSEARCH_CONFIG': '$AGENTIR_DIR/opensearch.yaml'},
}
p.write_text(yaml.dump(config, default_flow_style=False))
"
        echo "  Added opensearch-mcp to $GW_CONFIG"
    fi
else
    echo "Warning: Gateway config not found at $GW_CONFIG"
    echo "  opensearch-mcp must be registered manually."
    echo "  Add to gateway.yaml under 'backends:':"
    echo "    opensearch-mcp:"
    echo "      type: stdio"
    echo "      command: $HOME/.agentir/venv/bin/python"
    echo '      args: ["-m", "opensearch_mcp"]'
    echo '      env: {OPENSEARCH_CONFIG: ~/.agentir/opensearch.yaml}'
fi

# --- 10. Restart gateway if running ---
if systemctl --user is-active --quiet agentir-gateway 2>/dev/null; then
    echo "Restarting gateway to pick up opensearch-mcp..."
    systemctl --user restart agentir-gateway
    echo "  Gateway restarted."
elif pgrep -f "sift.gateway" >/dev/null 2>&1; then
    echo "Note: Gateway is running but not via systemd."
    echo "  Restart it manually to discover opensearch-mcp tools."
else
    echo "Note: Gateway is not running. opensearch-mcp will be"
    echo "  discovered when the gateway starts."
fi

# --- 11. Done ---
echo ""
echo "========================================="
echo "OpenSearch is running on $OS_URL"
echo "Config: $CONFIG_FILE"
echo "Security Analytics: Sigma rules available (detectors disabled — OpenSearch 3.5 regression). Detection via Hayabusa."
echo "GeoIP: enrichment pipeline configured (requires internet for DB download)"
echo ""
echo "NOTE: Existing indexed data does not have GeoIP. Re-ingest to enrich."
echo ""
echo "Next steps:"
echo "  opensearch-ingest /path/to/evtx/ --hostname SERVER01 --case incident-001"
echo "========================================="
